export const ADD_FAN_LETTER = 'ADD_FAN_LETTER';
export const UPDATE_FAN_LETTER = 'UPDATE_FAN_LETTER';
export const DELETE_FAN_LETTER = 'DELETE_FAN_LETTER';
export const SET_MODAL_VISIBILITY = 'SET_MODAL_VISIBILITY';
export const SET_MODAL_MESSAGE = 'SET_MODAL_MESSAGE';
